### PR TITLE
Blank page displayed in challenge iframe on IE first time

### PR DESCRIPTION
**Pull request by surajbyanju**
https://github.com/globalpayments/globalpayments-3ds-js/issues/3

### CODE REVIEW

**Review by slogsdon — APPROVED** [review]

**Comment by surajbyanju** [comment]
@slogsdon are you getting this deployed anytime soon?

**Comment by slogsdon** [comment]
@surajbyanju We're currently under an organization-wide code freeze through the end of the week. As long as it doesn't get extended, we should be able to get this update pushed out early next week.

**Comment by surajbyanju** [comment]
@slogsdon any news on when this will be deployed?

**Comment by slogsdon** [comment]
Apologies for not yet circling back. I am working with the team to get this deployed. I will circle back once it's available.

**Comment by slogsdon** [comment]
@surajbyanju This has been deployed to NPM as 1.0.4

**Comment by surajbyanju** [comment]
@slogsdon Thank you!!

**Pull request merged**
